version: "3"

services:
  app:
    build: .
    image: organization_chart
    container_name: organization_chart_app
    restart: always
    environment:
      STAGE: debug
      NEO4J_BOLT_URL: bolt://neo4j:organization_chart_pwd@neo:7687
    ports:
      - "8000:8000"
    volumes:
      - ./organization:/app
    depends_on:
      - neo
    networks:
      - organization_chart_network
    command: python manage.py runserver 0.0.0.0:8000

  neo:
    image: neo4j:3.5.5
    container_name: organization_chart_database
    restart: always
    environment:
      NEO4J_AUTH: neo4j/organization_chart_pwd
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ~/data/organization_chart/neo4j:/data
    networks:
      - organization_chart_network

networks:
  organization_chart_network:
    driver: bridge
